### Obtener datos
GET http://127.0.0.1:8000/api/datos
Accept: application/json
Authorization: Bearer 6|cMGIrwEa9lMDLfFq86VcFm9Seyky0TqH5udGnLny

### Obtener una dato
GET http://127.0.0.1:8000/api/datos/1
Accept: application/json
Authorization: Bearer 6|cMGIrwEa9lMDLfFq86VcFm9Seyky0TqH5udGnLny

### Crear una dato
POST http://127.0.0.1:8000/api/datos
Accept: application/json
Content-Type: application/json
Authorization: Bearer 6|cMGIrwEa9lMDLfFq86VcFm9Seyky0TqH5udGnLny

{
    "venta_id":1
    ,"cantidad":1
    ,"total":300
}

### Editar dato
PUT http://127.0.0.1:8000/api/datos/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 6|cMGIrwEa9lMDLfFq86VcFm9Seyky0TqH5udGnLny

{
    "venta_id":1
    ,"cantidad":1
    ,"total":300
}