### Obtener productos
GET http://127.0.0.1:8000/api/productos
Accept: application/json
Authorization: Bearer 5|FSodKx4aK95IyKU9rWrjwB44F2NBv8XQ3qfkicAo

### Obtener un producto
GET http://127.0.0.1:8000/api/productos/1
Accept: application/json
Authorization: Bearer 5|FSodKx4aK95IyKU9rWrjwB44F2NBv8XQ3qfkicAo

### Crear un producto
POST http://127.0.0.1:8000/api/productos
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|FSodKx4aK95IyKU9rWrjwB44F2NBv8XQ3qfkicAo

{
    "proveedor_id":1
    ,"producto":"Cepillo"
    ,"marca":"AmikoosVet"
    ,"precio":150
    ,"stock":15
}

### Editar un producto
PUT http://127.0.0.1:8000/api/productos/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 5|FSodKx4aK95IyKU9rWrjwB44F2NBv8XQ3qfkicAo

{
    "proveedor_id":1
    ,"producto":"Juguete"
    ,"marca":"AmikoosVet"
    ,"precio":150
    ,"stock":15
}